# Generated by Django 4.2.7 on 2024-04-04 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Frage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=250, verbose_name="Titel")),
                (
                    "inhalt",
                    models.CharField(default="?", max_length=50, verbose_name="Inhalt"),
                ),
                ("frage", models.TextField(verbose_name="Frage")),
                (
                    "musterantwort",
                    models.TextField(default="", verbose_name="Musterantwort"),
                ),
                (
                    "bild",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Bild"
                    ),
                ),
                (
                    "bildmuster",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Bild Muster"
                    ),
                ),
                (
                    "bildbreite",
                    models.IntegerField(default=80, verbose_name="Bildbreite in %"),
                ),
                (
                    "punkte",
                    models.IntegerField(default=1, verbose_name="Erreichbare Punkte"),
                ),
                (
                    "schwierigkeit",
                    models.IntegerField(default=2, verbose_name="Schwierigkeit"),
                ),
            ],
            options={
                "verbose_name": "Frage",
                "verbose_name_plural": "Fragen",
                "ordering": ["thema", "titel"],
            },
        ),
        migrations.CreateModel(
            name="Gruppe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Bezeichnung")),
            ],
            options={
                "verbose_name": "Gruppe",
                "verbose_name_plural": "Gruppen",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Klausur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titel", models.CharField(max_length=50, verbose_name="Titel")),
                ("thema", models.CharField(max_length=50, verbose_name="Thema")),
                ("termin", models.DateTimeField(verbose_name="termin")),
                (
                    "fragen",
                    models.ManyToManyField(to="klausur.frage", verbose_name="Fragen"),
                ),
                (
                    "gruppe",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klausur.gruppe",
                        verbose_name="Gruppe",
                    ),
                ),
            ],
            options={
                "verbose_name": "Klausur",
                "verbose_name_plural": "Klausuren",
                "ordering": ["gruppe", "-termin"],
            },
        ),
        migrations.CreateModel(
            name="Teilnehmer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Name")),
                ("info", models.TextField(blank=True, null=True, verbose_name="Infos")),
            ],
            options={
                "verbose_name": "Teilnehmer",
                "verbose_name_plural": "Teilnehmers",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Thema",
            fields=[
                (
                    "titel",
                    models.CharField(
                        max_length=250,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Titel",
                    ),
                ),
                (
                    "kommentar",
                    models.TextField(blank=True, null=True, verbose_name="Kommentar"),
                ),
            ],
            options={
                "verbose_name": "Thema",
                "verbose_name_plural": "Themas",
                "ordering": ["titel"],
            },
        ),
        migrations.CreateModel(
            name="Klausurthema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.IntegerField(default=1, verbose_name="Position")),
                (
                    "seitenwechsel",
                    models.BooleanField(
                        default=False, verbose_name="Seitenwechsel im Anschluss"
                    ),
                ),
                (
                    "frage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="klausur.frage",
                        verbose_name="Frage",
                    ),
                ),
                (
                    "klausur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klausur.klausur",
                        verbose_name="Klausur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Klausur-Thema",
                "verbose_name_plural": "Klausur-Themen",
                "ordering": ["klausur", "position"],
            },
        ),
        migrations.AddField(
            model_name="gruppe",
            name="teilnehmer",
            field=models.ManyToManyField(
                to="klausur.teilnehmer", verbose_name="Teilnehmer"
            ),
        ),
        migrations.AddField(
            model_name="frage",
            name="thema",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                to="klausur.thema",
                verbose_name="Thema",
            ),
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("punkte", models.IntegerField(default=0, verbose_name="Punkte")),
                (
                    "bemerkung",
                    models.TextField(blank=True, null=True, verbose_name="Bemerkung"),
                ),
                (
                    "frage",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klausur.frage",
                        verbose_name="Frage",
                    ),
                ),
                (
                    "klausur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klausur.klausur",
                        verbose_name="Klausur",
                    ),
                ),
                (
                    "teilnehmer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="klausur.teilnehmer",
                        verbose_name="Teilnhmer*in",
                    ),
                ),
            ],
            options={
                "verbose_name": "Antwort",
                "verbose_name_plural": "Antworten",
            },
        ),
    ]
